# Generated by Django 5.0.1 on 2024-01-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhometasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhometasks.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhometasks.product')),
            ],
        ),
    ]
