# Generated by Django 5.0.1 on 2024-01-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhometasks', '0002_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='myhometasks.OrderProduct', to='myhometasks.product'),
        ),
    ]
